import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="main-layout-wrapper">
          <main className="main-content-wrapper">{children}</main>
          <footer className="footer-wrapper">
            {/* Add your footer content here */}
            <p>&copy; 2023 My App</p>
          </footer>
        </div>
      </body>
    </html>
  );
}